// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFeSnFb63gndh9JBMiT9Q1lfKTLXaxNRs',
    appId: '1:535696404678:web:052b6826eb098e44b267c7',
    messagingSenderId: '535696404678',
    projectId: 't-allam',
    authDomain: 't-allam.firebaseapp.com',
    storageBucket: 't-allam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHW_fb_rk1oWjT74iWNFshprqwKXQiO0Q',
    appId: '1:535696404678:android:98ded023b58bc772b267c7',
    messagingSenderId: '535696404678',
    projectId: 't-allam',
    storageBucket: 't-allam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDERvTKNnSEas2Plm7FKlm-T9La-CNHaY',
    appId: '1:535696404678:ios:8ac6067e2364c0acb267c7',
    messagingSenderId: '535696404678',
    projectId: 't-allam',
    storageBucket: 't-allam.appspot.com',
    iosBundleId: 'com.example.tAllam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDERvTKNnSEas2Plm7FKlm-T9La-CNHaY',
    appId: '1:535696404678:ios:8ac6067e2364c0acb267c7',
    messagingSenderId: '535696404678',
    projectId: 't-allam',
    storageBucket: 't-allam.appspot.com',
    iosBundleId: 'com.example.tAllam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFeSnFb63gndh9JBMiT9Q1lfKTLXaxNRs',
    appId: '1:535696404678:web:aa7e450296ec7c9fb267c7',
    messagingSenderId: '535696404678',
    projectId: 't-allam',
    authDomain: 't-allam.firebaseapp.com',
    storageBucket: 't-allam.appspot.com',
  );
}
